#ifndef _CAUTERIZE_C11STREAM_helium_atom_api_DESCRIPTORS_
#define _CAUTERIZE_C11STREAM_helium_atom_api_DESCRIPTORS_

#include <stdint.h>

#include "cauterize_descriptors.h"

/* number of types */
#define TYPE_COUNT_helium_atom_api (124)

/* schema depth */
#define SCHEMA_DEPTH_helium_atom_api (9)

/* an index for each type */
enum type_id_helium_atom_api {
  type_id_helium_atom_api_bool = primitive_type_id_bool,
  type_id_helium_atom_api_f64 = primitive_type_id_f64,
  type_id_helium_atom_api_f32 = primitive_type_id_f32,
  type_id_helium_atom_api_s64 = primitive_type_id_s64,
  type_id_helium_atom_api_s32 = primitive_type_id_s32,
  type_id_helium_atom_api_s16 = primitive_type_id_s16,
  type_id_helium_atom_api_s8 = primitive_type_id_s8,
  type_id_helium_atom_api_u64 = primitive_type_id_u64,
  type_id_helium_atom_api_u32 = primitive_type_id_u32,
  type_id_helium_atom_api_u16 = primitive_type_id_u16,
  type_id_helium_atom_api_u8 = primitive_type_id_u8,
  type_id_helium_atom_api_s_ssk = 0,
  type_id_helium_atom_api_s_sig = 1,
  type_id_helium_atom_api_s_sigs = 2,
  type_id_helium_atom_api_s_sec_type = 3,
  type_id_helium_atom_api_s_part_num = 4,
  type_id_helium_atom_api_s_lstat = 5,
  type_id_helium_atom_api_s_key_sigs = 6,
  type_id_helium_atom_api_s_key_sig_req = 7,
  type_id_helium_atom_api_s_key_sig_req_rec = 8,
  type_id_helium_atom_api_s_gen_session_key_req = 9,
  type_id_helium_atom_api_power_cmd = 10,
  type_id_helium_atom_api_pan_frame = 11,
  type_id_helium_atom_api_pan_cmd = 12,
  type_id_helium_atom_api_n_send_tx_status = 13,
  type_id_helium_atom_api_n_send_req = 14,
  type_id_helium_atom_api_n_send_metadata = 15,
  type_id_helium_atom_api_n_send_err = 16,
  type_id_helium_atom_api_n_send_resp = 17,
  type_id_helium_atom_api_n_mode = 18,
  type_id_helium_atom_api_n_img_sha = 19,
  type_id_helium_atom_api_n_reflash_header = 20,
  type_id_helium_atom_api_n_img_id = 21,
  type_id_helium_atom_api_n_img_data = 22,
  type_id_helium_atom_api_n_reflash_data = 23,
  type_id_helium_atom_api_n_cmd_send = 24,
  type_id_helium_atom_api_n_cmd_reflash_header_resp = 25,
  type_id_helium_atom_api_n_cmd_reflash_header = 26,
  type_id_helium_atom_api_n_cmd_reflash_data_resp = 27,
  type_id_helium_atom_api_n_cmd_reflash_data = 28,
  type_id_helium_atom_api_n_cmd_get_mode = 29,
  type_id_helium_atom_api_n_cmd_connection_status_resp = 30,
  type_id_helium_atom_api_n_cmd_connection_status = 31,
  type_id_helium_atom_api_n_cmd_connect_resp = 32,
  type_id_helium_atom_api_h_scan = 33,
  type_id_helium_atom_api_h_mfg_data = 34,
  type_id_helium_atom_api_h_mac = 35,
  type_id_helium_atom_api_s_get_derived_key_req = 36,
  type_id_helium_atom_api_h_data_u8 = 37,
  type_id_helium_atom_api_h_data_u32 = 38,
  type_id_helium_atom_api_h_data_u16 = 39,
  type_id_helium_atom_api_h_buf_32b = 40,
  type_id_helium_atom_api_s_key_update_req = 41,
  type_id_helium_atom_api_h_buf_20b = 42,
  type_id_helium_atom_api_h_buf = 43,
  type_id_helium_atom_api_h_arr_32b = 44,
  type_id_helium_atom_api_beacon_cmd = 45,
  type_id_helium_atom_api_a_version = 46,
  type_id_helium_atom_api_n_connection = 47,
  type_id_helium_atom_api_n_cmd_sleep_resp = 48,
  type_id_helium_atom_api_n_cmd_sleep = 49,
  type_id_helium_atom_api_n_connection_quick = 50,
  type_id_helium_atom_api_n_cmd_connect_req = 51,
  type_id_helium_atom_api_n_cmd_connect = 52,
  type_id_helium_atom_api_a_time = 53,
  type_id_helium_atom_api_a_status = 54,
  type_id_helium_atom_api_r_cmd_get_info_resp = 55,
  type_id_helium_atom_api_s_gen_session_key_resp = 56,
  type_id_helium_atom_api_s_cmd_gen_session_key = 57,
  type_id_helium_atom_api_s_get_derived_key_resp = 58,
  type_id_helium_atom_api_s_cmd_get_derived_key = 59,
  type_id_helium_atom_api_s_key_sig_resp = 60,
  type_id_helium_atom_api_s_cmd_key_sigs = 61,
  type_id_helium_atom_api_s_resp_key_create = 62,
  type_id_helium_atom_api_s_cmd_key_create = 63,
  type_id_helium_atom_api_s_resp_lstat = 64,
  type_id_helium_atom_api_s_cmd_read_lstat = 65,
  type_id_helium_atom_api_s_resp_part = 66,
  type_id_helium_atom_api_s_cmd_read_part = 67,
  type_id_helium_atom_api_a_sleep_mode = 68,
  type_id_helium_atom_api_a_resp_u8 = 69,
  type_id_helium_atom_api_a_resp_u64 = 70,
  type_id_helium_atom_api_a_resp_sleep_mode = 71,
  type_id_helium_atom_api_a_resp_mfg_data = 72,
  type_id_helium_atom_api_a_resp_get_atom_info = 73,
  type_id_helium_atom_api_a_resp_gen = 74,
  type_id_helium_atom_api_n_cmd_set_mode = 75,
  type_id_helium_atom_api_r_cmd_beacon = 76,
  type_id_helium_atom_api_r_cmd_pan = 77,
  type_id_helium_atom_api_r_cmd_pan_fr = 78,
  type_id_helium_atom_api_r_cmd_power = 79,
  type_id_helium_atom_api_r_cmd_scan_start = 80,
  type_id_helium_atom_api_r_cmd_set_chan = 81,
  type_id_helium_atom_api_r_cmd_set_pan_id = 82,
  type_id_helium_atom_api_r_cmd_set_sh_addr = 83,
  type_id_helium_atom_api_s_cmd_init = 84,
  type_id_helium_atom_api_s_cmd_key_update = 85,
  type_id_helium_atom_api_s_cmd_lock = 86,
  type_id_helium_atom_api_a_radio_type = 87,
  type_id_helium_atom_api_r_cmd_get_info = 88,
  type_id_helium_atom_api_r_cmd = 89,
  type_id_helium_atom_api_a_op_mode = 90,
  type_id_helium_atom_api_a_debug_msg = 91,
  type_id_helium_atom_api_a_data = 92,
  type_id_helium_atom_api_n_poll_data = 93,
  type_id_helium_atom_api_n_cmd_poll_data_resp = 94,
  type_id_helium_atom_api_n_cmd_poll_data = 95,
  type_id_helium_atom_api_a_cmd_security = 96,
  type_id_helium_atom_api_a_cmd_radio = 97,
  type_id_helium_atom_api_a_cmd_pin = 98,
  type_id_helium_atom_api_a_cmd_node = 99,
  type_id_helium_atom_api_a_cmd_config_set_time = 100,
  type_id_helium_atom_api_a_cmd_config_set_sleep_mode = 101,
  type_id_helium_atom_api_a_cmd_config_set_op_mode = 102,
  type_id_helium_atom_api_a_cmd_config_set_mfg_data = 103,
  type_id_helium_atom_api_a_cmd_config_set_mac = 104,
  type_id_helium_atom_api_a_cmd_config_read_sleep_mode = 105,
  type_id_helium_atom_api_a_cmd_config_read_mfg_data = 106,
  type_id_helium_atom_api_a_cmd_config_read_mac = 107,
  type_id_helium_atom_api_a_cmd_config_get_atom_info = 108,
  type_id_helium_atom_api_a_cmd_brd_reset = 109,
  type_id_helium_atom_api_a_cmd_brd_pin_out = 110,
  type_id_helium_atom_api_a_cmd_brd_pin_in = 111,
  type_id_helium_atom_api_a_cmd_board = 112,
  type_id_helium_atom_api_a_channel_report = 113,
  type_id_helium_atom_api_a_channel_reports = 114,
  type_id_helium_atom_api_a_beacon_report = 115,
  type_id_helium_atom_api_a_beacon_reports = 116,
  type_id_helium_atom_api_a_scan_report = 117,
  type_id_helium_atom_api_a_baud_rate = 118,
  type_id_helium_atom_api_a_cmd_config_read_baud_rate = 119,
  type_id_helium_atom_api_a_cmd_config_set_baud_rate = 120,
  type_id_helium_atom_api_a_cmd_config = 121,
  type_id_helium_atom_api_a_cmd = 122,
  type_id_helium_atom_api_a_cmd_t = 123,
};


/* a descriptor for the entire schema */
extern struct schema_descriptor const schema_descriptor_helium_atom_api;

#endif /* _CAUTERIZE_C11STREAM_helium_atom_api_DESCRIPTORS_ */
